### ISSUE TITLE
Sidebar links hidden when navigate to folder structure page

### ISSUE THREAD

**Issue by manojsinghnegiwd** [recraftrelic/recraft-chat-app-documentation#4]
https://documentation.recraftrelic.com/chatapp/docs/Folder_Structure/

Not able to see pages, themes, components links in the sidebar

![Screenshot 2020-04-14 at 2 41 57 AM](https://user-images.githubusercontent.com/7533769/79161691-8d597400-7df9-11ea-896d-8317486952b9.png)

**Comment by yashkapoor8710** [comment]
![Screenshot 2020-04-14 at 10 43 55 AM](https://user-images.githubusercontent.com/59904360/79188530-dc74c880-7e3c-11ea-9070-9d0f89ffc7bb.png)

I have added the links in the sidebar just need to refresh that's it
