### ISSUE TITLE
Remove unwanted things from the chat app documentation homepage

### ISSUE THREAD

**Issue by manojsinghnegiwd** [recraftrelic/recraft-chat-app-documentation#5]
Just keep this section and replace the mobile part with our application video and the left hand side part with description of our app and links to google play and our docs

![Screenshot 2020-04-14 at 2 44 54 AM](https://user-images.githubusercontent.com/7533769/79161939-f93bdc80-7df9-11ea-9b3e-e8c078e25ffc.png)

**Comment by yashkapoor8710** [comment]
This issue is fixed
https://github.com/recraftrelic/recraft-chat-app-documentation/pull/3
